import React from 'react'
import { SliderData } from './SliderData'


const Slider = ({data}) => {
  return (
    <div id='gallery'>
    <div>
        <h1 className='text-5xl font-bold'>ABOUT MANDAV</h1>
       An inscription discovered from Talanpur (around 100 km from Mandu) states that a merchant named Chandra Simha installed a statue in a temple of Parshvanatha located in the Mandapa Durg. While Durg means Fort, the word Mandu is a Prakrit corruption of mandapa, meaning hall, temple. The inscription is dated 612 VS (555 CE), which indicates that Mandu was a flourishing town in 6th century.Mandu gained prominence in 10th and 11th century under the Paramaras. The town of Mandu, situated at an elevation of 633 metres (2,079 feet), is perched on the Vindhya Range extending for 13 km (8.1 mi) while overlooking the plateau of Malwa to the north and the valley of the Narmada River to the south which acted as natural defences for the fort-capital the Paramaras. As "Mandapa-Durga", Mandu is mentioned as the royal residence in the inscriptions of the Paramara kings starting from Jayavarman II. It is possible that Jayavarman or his predecessor Jaitugi moved from the traditional Paramara capital Dhara to Mandu, because of attacks from the neighbouring kingdoms. Balban, the general of the Delhis Sultan Nasir-ud-din, had reached the northern frontier of the Paramara territory by this time. Around the same time, the Paramaras also faced attacks from the Yadava king Krishna of Deogiri and the Vaghela king Visaladeva of Gujarat. Compared to Dhara, which is located in the plains, the hilly area of Mandu would have offered a better defensive position.In 1305, the Muslim Sultan of Delhi Alauddin Khalji captured Malwa, the Paramara territory. Ayn al-Mulk Multani, the newly appointed Governor of Malwa, was sent to expel the Paramara king Mahalakadeva from Mandu and cleanse that place from "the odour of infidelity". With the help of a spy, Multanis forces found a way to enter the fort secretly. Mahalakadeva was killed while attempting to flee, on 24 November 1305. When Timur captured Delhi in 1401, the Afghan Dilawar Khan, governor of Malwa, set up his own little kingdom and the Ghuri dynasty was established, His son, Hoshang Shah, shifted the capital from Dhar to Mandu and raised it to its greatest splendour. His son and third and last ruler of Ghuri dynasty, Mohammed, ruled for just one year till his poisoning by the militaristic Mohammed Khalji.
       </div>
      <div>
       <h1 className='text-5xl font-bold flex'>PLACES OF INTEREST</h1>
       Mandu, due to its strategic position and natural defences, was an important place with a rich and varied history. It was an important military outpost and its military past can be gauged by the circuit of the battlemented wall, which is nearly 37 km (23 mi) and is punctuated by 12 gateways. The wall encloses a large number of palaces, mosques, Jain temples of 14th century and other buildings. The oldest mosque dates from 1405; the finest is the Jama Masjid or great mosque, a notable example of Pashtun architecture. The marble-domed tomb of this ruler is also magnificent Some of the notable places, listed in South to North direction are: 1) Roopmatis Pavilion A large sandstone structure originally built as an army observation post it is known today as Roopmatis Pavilion. Rani Roopmati - the love interest of Baaz Bahadur lived here and is said to have gazed at the Baz Bahadurs Palace - situated below and also at Narmada river, flowing through the Nimar plains far below, a river which the queen revered.Baz Bahadurs Palace Built by Baz Bahadur, this 16th-century structure is famous for its large courtyards encompassed by large halls and high terraces. It is situated below Roopmatis Pavilion and can be seen from the pavilion.Rewa Kund A reservoir constructed by Baz Bahadur for the purpose of supplying water to Rani Roopmatis Pavilion. The reservoir is situated below the pavilion and hence is considered an architectural marvel. Darya Khans Tomb complex : Darya Khan was a minister in the court of Mahmud Khalji II, and his tomb lies in a walled complex along with another tomb, a mosque, a pond, and an inn. At the centre of the complex is the massive sandstone tomb of Darya Khan. Hathi Paga Mahal or Elephant Leg Palace is located on the south-eastern side of the Darya Khan Complex, and is crowned with a massive dome. Shri Mandavagadh Teerth: Shri Mandavagadh Teerth is dedicated to Lord Suparshvanatha. It belongs to Shwetambar sect of Jainism. The temple has been attractively constructed and looks exquisite. It underwent expansion in 14th century. The idol of Lord Suparshvanath is believed to be much older. The idol is white in complexion and is 91.54 cm (3 feet) in height. It is seated in a padmansana posture. Apart from this in this same fort there is a fine temple of smaller size of Lord Shantinath. Ruins of many temples and idols can be seen here. As per a reference once there were almost 700 Jain temples here.
    </div>
    </div>
  )
}

export default Slider